import {
  Home,
  Cpu,
  Wrench,
  List,
  Package,
  Crosshair,
  TrendingUp,
  Heart,
  Settings,
  Palette,
  Layout,
  Zap,
  MousePointer2,
  MousePointerClick,
  Monitor,
  Download,
  Video,
  Network,
  Bot,
  Volume2,
  Trash2,
  MemoryStick,
  Gauge,
  Gamepad2,
  Battery,
  Music,
  HardDrive,
  Settings2,
  Tv2,
  Thermometer,
  Activity,
  Eraser,
  Scaling,
  Search,
  Scissors,
  Boxes,
  Braces,
  PieChart,
  Archive,
  Rocket,
  LineChart,
  ShieldCheck,
  FlaskConical,
  Ban,
} from "lucide-react";
import type { ComponentType } from "react";

export type SearchCategory = "page" | "builtin-tool" | "optimization" | "thirdparty-tool";

export interface SearchItem {
  id: string;
  nameKey: string;
  path: string;
  icon: ComponentType<{ size?: number; strokeWidth?: number }>;
  category: SearchCategory;
  keywords?: string[];
  customIcon?: string;
  action?: "navigate" | "run-tool";
  toolId?: string;
}

export const searchIndex: SearchItem[] = [
  {
    id: "home",
    nameKey: "sidebar.home",
    path: "/",
    icon: Home,
    category: "page",
    keywords: ["首页", "主页", "home", "main"],
  },
  {
    id: "hardware",
    nameKey: "sidebar.hardware",
    path: "/hardware",
    icon: Cpu,
    category: "page",
    keywords: ["硬件", "信息", "hardware", "cpu", "gpu", "显卡", "处理器"],
  },
  {
    id: "tools",
    nameKey: "sidebar.tools",
    path: "/tools",
    icon: Wrench,
    category: "page",
    keywords: ["工具", "tools", "工具箱"],
  },
  {
    id: "builtin-tools",
    nameKey: "sidebar.builtinTools",
    path: "/builtin-tools",
    icon: Package,
    category: "page",
    keywords: ["内置", "工具", "builtin", "tools"],
  },
  {
    id: "optimization",
    nameKey: "sidebar.optimization",
    path: "/optimization",
    icon: TrendingUp,
    category: "page",
    keywords: ["优化", "optimization", "性能"],
  },
  {
    id: "delta-force",
    nameKey: "sidebar.deltaForce",
    path: "/delta-force",
    icon: Crosshair,
    category: "page",
    keywords: ["三角洲", "delta", "force", "密码", "改枪码"],
  },
  {
    id: "epic-free",
    nameKey: "sidebar.epicFree",
    path: "/epic-free",
    icon: Gamepad2,
    category: "page",
    keywords: ["epic", "喜加一", "免费", "游戏", "free", "games", "白嫖"],
  },
  {
    id: "steam",
    nameKey: "sidebar.steam",
    path: "/steam",
    icon: Gamepad2,
    category: "page",
    keywords: ["steam", "Steam管理", "游戏管理", "账户", "游戏库", "库", "已安装", "卸载"],
  },
  {
    id: "music",
    nameKey: "sidebar.music",
    path: "/music",
    icon: Music,
    category: "page",
    keywords: ["音乐", "播放器", "music", "player", "网易云", "netease", "咪咕", "migu", "酷狗", "kugou", "QQ音乐"],
  },
  {
    id: "sponsor",
    nameKey: "settings.sponsor",
    path: "/settings",
    icon: Heart,
    category: "page",
    keywords: ["赞助", "sponsor", "支持", "捐赠", "打赏", "donate", "support"],
  },
  {
    id: "settings",
    nameKey: "sidebar.settings",
    path: "/settings",
    icon: Settings,
    category: "page",
    keywords: ["设置", "settings", "配置"],
  },
  {
    id: "display-filter",
    nameKey: "sidebar.displayFilter",
    path: "/display-filter",
    icon: Palette,
    category: "builtin-tool",
    keywords: ["滤镜", "显示器", "display", "filter", "色彩", "色温"],
  },
  {
    id: "crosshair",
    nameKey: "sidebar.crosshair",
    path: "/crosshair",
    icon: Crosshair,
    category: "builtin-tool",
    keywords: ["准心", "准星", "crosshair", "瞄准"],
  },
  {
    id: "autoclicker",
    nameKey: "sidebar.autoclicker",
    path: "/autoclicker",
    icon: MousePointerClick,
    category: "builtin-tool",
    keywords: ["连点器", "连点", "自动点击", "鼠标", "点击", "autoclicker", "clicker", "连发", "cps"],
  },
  {
    id: "overlay-panel",
    nameKey: "sidebar.overlayPanel",
    path: "/overlay-panel",
    icon: Layout,
    category: "builtin-tool",
    keywords: ["悬浮", "overlay", "面板", "监控"],
  },
  {
    id: "gpu-rename",
    nameKey: "sidebar.gpuRename",
    path: "/gpu-rename",
    icon: Cpu,
    category: "builtin-tool",
    keywords: ["显卡", "改写", "gpu", "rename", "伪装"],
  },
  {
    id: "nvidia-driver",
    nameKey: "sidebar.nvidiaDriver",
    path: "/nvidia-driver",
    icon: Tv2,
    category: "builtin-tool",
    keywords: ["显卡设置", "nvidia", "驱动", "垂直同步", "纹理", "抗锯齿", "fxaa", "帧率", "电源", "各向异性过滤", "nvapi", "3d设置", "g-sync", "vr", "分辨率", "显示器", "切换分辨率", "resolution"],
  },
  {
    id: "resolution-converter",
    nameKey: "sidebar.resolutionConverter",
    path: "/resolution-converter",
    icon: Monitor,
    category: "builtin-tool",
    keywords: ["分辨率", "换算", "resolution", "converter", "比例"],
  },
  {
      id: "dlss-preset",
      nameKey: "sidebar.dlssPreset",
      path: "/dlss-preset",
      icon: Zap,
      category: "builtin-tool",
      keywords: ["dlss", "预设", "preset", "三角洲", "delta", "force", "nvidia", "模型"],
    },
  {
    id: "audio-eq",
    nameKey: "sidebar.audioEq",
    path: "/audio-eq",
    icon: Volume2,
    category: "builtin-tool",
    keywords: ["EQ", "调音", "均衡器", "音频", "声卡", "equalizer", "audio", "fxsound", "音效"],
  },
  {
    id: "nvidia-driver-download",
    nameKey: "sidebar.nvidiaDriverDownload",
    path: "/nvidia-driver-download",
    icon: Download,
    category: "builtin-tool",
    keywords: ["nvidia", "驱动下载", "显卡驱动", "下载驱动", "下载", "历史版本", "geforce", "driver", "download", "英伟达"],
  },
  {
    id: "nvidia-recording",
    nameKey: "sidebar.nvidiaRecording",
    path: "/nvidia-recording",
    icon: Video,
    category: "builtin-tool",
    keywords: ["n卡", "nvidia", "英伟达", "录制", "录制管理", "回放", "高光", "视频", "instant replay", "recording", "清理"],
  },
  {
    id: "memory-limit",
    nameKey: "optimization.memoryLimit.title",
    path: "/optimize/memory-limit",
    icon: Cpu,
    category: "optimization",
    keywords: ["内存", "限制", "memory", "limit", "优化"],
  },
  {
    id: "memory-cleanup",
    nameKey: "optimization.memoryCleanup.title",
    path: "/optimize/memory-cleanup",
    icon: MemoryStick,
    category: "optimization",
    keywords: ["内存", "清理", "memory", "cleanup", "释放", "优化"],
  },
  {
    id: "ace-optimize",
    nameKey: "optimization.aceOptimize.title",
    path: "/optimize/ace-optimize",
    icon: Gauge,
    category: "optimization",
    keywords: ["ace", "优化", "反作弊", "sguard", "进程"],
  },
  {
    id: "game-process-optimize",
    nameKey: "optimization.gameProcessOptimize.title",
    path: "/optimize/game-process-optimize",
    icon: Gamepad2,
    category: "optimization",
    keywords: ["游戏", "进程优化", "核心", "优先级", "三角洲", "delta", "game", "process", "affinity", "自动优化"],
  },
  {
    id: "shader-cache",
    nameKey: "shaderCache.title",
    path: "/optimize/shader-cache",
    icon: Trash2,
    category: "optimization",
    keywords: ["着色器", "缓存", "shader", "cache", "清理", "nvidia", "amd"],
  },
  {
    id: "power-management",
    nameKey: "optimization.powerManagement.title",
    path: "/optimize/power-management",
    icon: Battery,
    category: "optimization",
    keywords: ["电源", "管理", "power", "management", "电源计划", "高性能", "处理器", "CPU", "散热", "boost", "睿频", "核心停放", "高级设置"],
  },
  {
    id: "storage-clean",
    nameKey: "storageClean.title",
    path: "/optimize/storage-clean",
    icon: HardDrive,
    category: "optimization",
    keywords: ["存储", "清理", "storage", "clean", "磁盘", "垃圾", "临时文件", "缓存"],
  },
  {
    id: "startup-manager",
    nameKey: "optimization.startupManager.title",
    path: "/optimize/startup-manager",
    icon: List,
    category: "optimization",
    keywords: ["启动", "startup", "开机自启", "管理"],
  },
  {
    id: "system-optimizer",
    nameKey: "systemOptimizer.pageTitle",
    path: "/optimize/system-optimizer",
    icon: Settings2,
    category: "optimization",
    keywords: ["系统优化", "system", "optimizer", "注册表", "服务", "性能", "隐私", "游戏", "一键优化"],
  },
  {
    id: "windows-update",
    nameKey: "windowsUpdate.pageTitle",
    path: "/optimize/windows-update",
    icon: Download,
    category: "optimization",
    keywords: ["关闭更新", "禁用更新", "windows更新", "自动更新", "Windows Update", "wuauserv", "停止更新", "系统更新"],
  },
  {
    id: "speedtest",
    nameKey: "sidebar.speedtest",
    path: "/speedtest",
    icon: Gauge,
    category: "builtin-tool",
    keywords: ["测速", "网速", "speed", "test", "宽带", "延迟", "下载", "上传", "ping", "jitter", "丢包"],
  },
  {
    id: "runtime-repair",
    nameKey: "sidebar.runtimeRepair",
    path: "/runtime-repair",
    icon: Braces,
    category: "builtin-tool",
    keywords: ["运行库", "运行库修复", "运行库补全", "vc++", "vc", "redist", "visual c++", "directx", "dx", ".net", "net framework", "runtime", "修复", "缺失", "库"],
  },
  {
    id: "vtx-virtualization",
    nameKey: "sidebar.vtxVirtualization",
    path: "/vtx-virtualization",
    icon: ShieldCheck,
    category: "builtin-tool",
    keywords: ["VT-X", "vt-x", "VTX", "虚拟化", "virtualization", "内存完整性", "内核隔离", "hypervisor", "hyper-v", "hyperv", "VBS", "HypervisorEnforcedCodeIntegrity", "弹窗", "反作弊", "安全中心"],
  },
  {
    id: "hidden-features",
    nameKey: "sidebar.hiddenFeatures",
    path: "/hidden-features",
    icon: FlaskConical,
    category: "builtin-tool",
    keywords: ["隐藏功能", "功能开关", "feature flag", "featureflags", "vivetool", "vive", "velocity", "实验功能", "A/B", "feature id", "功能配置", "hidden features"],
  },
  {
    id: "context-menu",
    nameKey: "sidebar.contextMenu",
    path: "/context-menu",
    icon: MousePointer2,
    category: "builtin-tool",
    keywords: ["右键菜单", "右键", "context", "menu", "shell", "此电脑", "网盘", "onedrive", "命名空间", "namespace"],
  },
  {
    id: "network-optimizer",
    nameKey: "networkOptimize.pageTitle",
    path: "/optimize/network-optimizer",
    icon: Network,
    category: "optimization",
    keywords: ["网络优化", "network", "dns", "tcp", "延迟", "网速", "域名", "解析"],
  },
  {
    id: "peripheral-optimize",
    nameKey: "peripheralOptimize.pageTitle",
    path: "/optimize/peripheral-optimize",
    icon: MousePointer2,
    category: "optimization",
    keywords: ["外设", "鼠标", "键盘", "peripheral", "mouse", "keyboard", "注册表", "优化", "输入延迟", "Win32PrioritySeparation", "KeyboardDataQueueSize", "MouseDataQueueSize"],
  },
  {
    id: "cpu-scheduler",
    nameKey: "optimization.cpuScheduler.title",
    path: "/optimize/cpu-scheduler",
    icon: Cpu,
    category: "optimization",
    keywords: ["CPU", "核心", "调度", "P核", "E核", "亲和性", "affinity", "core", "scheduler", "逻辑处理器", "进程分配"],
  },
  {
    id: "download-accelerator",
    nameKey: "sidebar.downloadAccelerator",
    path: "/download-accelerator",
    icon: Download,
    category: "builtin-tool",
    keywords: ["下载加速", "多线程下载", "下载器", "分段下载", "满速", "下载", "download", "accelerator", "idm", "多线程"],
  },
  {
    id: "nexbox-popnull",
    nameKey: "settings.advanced.popnull.title",
    path: "/settings?section=advanced",
    icon: Ban,
    category: "page",
    keywords: [
      "弹窗", "拦截", "广告", "弹窗拦截", "拒弹窗", "popup", "popnull",
      "黑名单", "白名单", "blacklist", "whitelist", "拦广告",
      "flashcenter", "minipage", "热点", "NexBoxPopNull",
    ],
  },
];

export const thirdPartyToolIcons: Record<string, ComponentType<{ size?: number; strokeWidth?: number }>> = {
  "memreduct": Zap,
  "windows-core-optimizer": Cpu,
  "optimizer": TrendingUp,
  "cpu-z": Cpu,
  "gpu-z": Monitor,
  "gamepp": Bot,
  "fxsound": Volume2,
  "process-lasso": Cpu,
  "hwinfo": Cpu,
  "crystaldiskinfo": HardDrive,
  "core-temp": Thermometer,
  "aida64": Activity,
  "ddu": Eraser,
  "lossless-scaling": Scaling,
  "everything": Search,
  "dismpp": Settings2,
  "snipaste": Scissors,
  "powertoys": Boxes,
  "wiztree": PieChart,
  "7zip": Archive,
  "watt-toolkit": Rocket,
  "trafficmonitor": Gauge,
  "rtss": LineChart,
  "playnite": Gamepad2,
};

export function getThirdPartyToolIcon(toolId: string): ComponentType<{ size?: number; strokeWidth?: number }> {
  return thirdPartyToolIcons[toolId] || Wrench;
}

export const categoryLabels: Record<SearchCategory, string> = {
  "page": "search.categories.pages",
  "builtin-tool": "search.categories.builtinTools",
  "optimization": "search.categories.optimization",
  "thirdparty-tool": "search.categories.thirdpartyTools",
};

export const categoryOrder: SearchCategory[] = [
  "page",
  "builtin-tool",
  "optimization",
  "thirdparty-tool",
];
