import type { ComponentType } from "react";
import {
  Zap,
  Clock,
  Network,
  AlertTriangle,
  Shield,
  Printer,
  Phone,
  ShieldOff,
  HardDrive,
  Cpu,
  FileText,
  Radio,
  MonitorOff,
  Activity,
  Server,
  Eye,
  Layout,
  MessageSquare,
  Chrome,
  Monitor,
  Code,
  Pen,
  Gamepad2,
  Gamepad,
  Video,
  Power,
  MousePointer,
  Camera,
  Map as MapIcon,
  Search,
  Megaphone,
  SlidersHorizontal,
  MicOff,
  Sparkles,
  CloudOff,
  Image as ImageIcon,
  Bot,
  CameraOff,
  Ban,
  Brain,
  Cog,
  Plug,
  Boxes,
  Globe,
  Layers,
  Keyboard,
} from "lucide-react";

export type OptimizerCategory =
  | "gaming"
  | "nvidia"
  | "amd"
  | "intel"
  | "performance"
  | "privacy"
  | "ai"
  | "services"
  | "disk"
  | "apps";

export interface OptimizerItem {
  id: string;
  regName: string;
  category: OptimizerCategory;
  icon: ComponentType<{ size?: number; strokeWidth?: number }>;
  color: string;
  titleKey: string;
  descKey: string;
  /** 风险等级：low 低风险 | medium 中风险 | high 高风险 */
  risk: "low" | "medium" | "high";
  /** 渲染类型：toggle（默认开关）| select（下拉选择） */
  type?: "toggle" | "select";
  /** select 类型的选项列表 */
  options?: {
    value: string;
    labelKey: string;
    regName: string;
  }[];
  /** select 类型的默认选中值 */
  defaultSelectValue?: string;
}

// 预定义颜色池（固定顺序，避免刷新变化）
const COLORS = [
  "#FF6B9D", "#3182CE", "#38A169", "#DD6B20", "#805AD5",
  "#E53E3E", "#00B5D8", "#D69E2E", "#319795", "#667EEA",
  "#ED64A6", "#F56565", "#48BB78", "#9F7AEA", "#F6AD55",
];

export const optimizerItems: OptimizerItem[] = [
  // ============== 游戏与图形优化（12 项） ==============
  {
    id: "mmcssGameConfig",
    regName: "mmcssGameConfig",
    category: "gaming",
    icon: Gamepad2,
    color: COLORS[0],
    titleKey: "systemOptimizer.gaming.mmcssGameConfig",
    descKey: "systemOptimizer.gaming.mmcssGameConfigDesc",
    risk: "low",
  },
  {
    id: "gamePriority",
    regName: "gamePriority",
    category: "gaming",
    icon: Gamepad2,
    color: COLORS[1],
    titleKey: "systemOptimizer.gaming.gamePriority",
    descKey: "systemOptimizer.gaming.gamePriorityDesc",
    risk: "low",
  },
  {
    id: "directXAutoHDR",
    regName: "directXAutoHDR",
    category: "gaming",
    icon: Monitor,
    color: COLORS[3],
    titleKey: "systemOptimizer.gaming.directXAutoHDR",
    descKey: "systemOptimizer.gaming.directXAutoHDRDesc",
    risk: "low",
  },
  {
    id: "directXFlipModel",
    regName: "directXFlipModel",
    category: "gaming",
    icon: Monitor,
    color: COLORS[4],
    titleKey: "systemOptimizer.gaming.directXFlipModel",
    descKey: "systemOptimizer.gaming.directXFlipModelDesc",
    risk: "low",
  },
  {
    id: "directXVRR",
    regName: "directXVRR",
    category: "gaming",
    icon: Monitor,
    color: COLORS[5],
    titleKey: "systemOptimizer.gaming.directXVRR",
    descKey: "systemOptimizer.gaming.directXVRRDesc",
    risk: "low",
  },
  {
    id: "disableDXMaxWindow",
    regName: "disableDXMaxWindow",
    category: "gaming",
    icon: MonitorOff,
    color: COLORS[6],
    titleKey: "systemOptimizer.gaming.disableDXMaxWindow",
    descKey: "systemOptimizer.gaming.disableDXMaxWindowDesc",
    risk: "low",
  },
  {
    id: "disableGPUPreemption",
    regName: "disableGPUPreemption",
    category: "gaming",
    icon: Cpu,
    color: COLORS[7],
    titleKey: "systemOptimizer.gaming.disableGPUPreemption",
    descKey: "systemOptimizer.gaming.disableGPUPreemptionDesc",
    risk: "medium",
  },
  {
    id: "disableGameBar",
    regName: "disableGameBar",
    category: "gaming",
    icon: Gamepad,
    color: COLORS[8],
    titleKey: "systemOptimizer.gaming.disableGameBar",
    descKey: "systemOptimizer.gaming.disableGameBarDesc",
    risk: "low",
  },
  {
    id: "disableGameDVR",
    regName: "disableGameDVR",
    category: "gaming",
    icon: Video,
    color: COLORS[9],
    titleKey: "systemOptimizer.gaming.disableGameDVR",
    descKey: "systemOptimizer.gaming.disableGameDVRDesc",
    risk: "low",
  },
  {
    id: "disableBcastDVR",
    regName: "disableBcastDVR",
    category: "gaming",
    icon: Radio,
    color: COLORS[10],
    titleKey: "systemOptimizer.gaming.disableBcastDVR",
    descKey: "systemOptimizer.gaming.disableBcastDVRDesc",
    risk: "low",
  },
  {
    id: "disableAutoColorMgmt",
    regName: "disableAutoColorMgmt",
    category: "gaming",
    icon: Eye,
    color: COLORS[11],
    titleKey: "systemOptimizer.gaming.disableAutoColorMgmt",
    descKey: "systemOptimizer.gaming.disableAutoColorMgmtDesc",
    risk: "low",
  },
  {
    id: "gameMode",
    regName: "gameMode",
    category: "gaming",
    icon: Gamepad2,
    color: COLORS[12],
    titleKey: "systemOptimizer.gaming.gameMode",
    descKey: "systemOptimizer.gaming.gameModeDesc",
    risk: "low",
  },
  {
    id: "win32Priority",
    regName: "调整处理器以获得最佳性能",
    category: "gaming",
    icon: Cpu,
    color: COLORS[13],
    titleKey: "systemOptimizer.gaming.win32Priority",
    descKey: "systemOptimizer.gaming.win32PriorityDesc",
    risk: "low",
    type: "select",
    defaultSelectValue: "program",
    options: [
      {
        value: "program",
        labelKey: "systemOptimizer.gaming.win32PriorityProgram",
        regName: "win32Priority_program",
      },
      {
        value: "background",
        labelKey: "systemOptimizer.gaming.win32PriorityBackground",
        regName: "win32Priority_background",
      },
      {
        value: "extreme",
        labelKey: "systemOptimizer.gaming.win32PriorityExtreme",
        regName: "win32Priority_extreme",
      },
    ],
  },
  {
    id: "systemResponsiveness",
    regName: "systemResponsiveness",
    category: "gaming",
    icon: Activity,
    color: COLORS[14],
    titleKey: "systemOptimizer.gaming.systemResponsiveness",
    descKey: "systemOptimizer.gaming.systemResponsivenessDesc",
    risk: "low",
  },
  {
    id: "hags",
    regName: "hags",
    category: "gaming",
    icon: Monitor,
    color: COLORS[0],
    titleKey: "systemOptimizer.gaming.hags",
    descKey: "systemOptimizer.gaming.hagsDesc",
    risk: "low",
  },
  {
    id: "backgroundServices",
    regName: "backgroundServices",
    category: "gaming",
    icon: Server,
    color: COLORS[1],
    titleKey: "systemOptimizer.gaming.backgroundServices",
    descKey: "systemOptimizer.gaming.backgroundServicesDesc",
    risk: "low",
  },
  {
    id: "disableMpo",
    regName: "disableMpo",
    category: "gaming",
    icon: Layers,
    color: COLORS[2],
    titleKey: "systemOptimizer.gaming.disableMpo",
    descKey: "systemOptimizer.gaming.disableMpoDesc",
    risk: "medium",
  },

  // ============== NVIDIA 显卡优化（11 项） ==============
  {
    id: "lowLatencyThreshold",
    regName: "lowLatencyThreshold",
    category: "nvidia",
    icon: Zap,
    color: COLORS[0],
    titleKey: "systemOptimizer.nvidia.lowLatencyThreshold",
    descKey: "systemOptimizer.nvidia.lowLatencyThresholdDesc",
    risk: "low",
  },
  {
    id: "perCpuDPC",
    regName: "perCpuDPC",
    category: "nvidia",
    icon: Cpu,
    color: COLORS[1],
    titleKey: "systemOptimizer.nvidia.perCpuDPC",
    descKey: "systemOptimizer.nvidia.perCpuDCPDesc",
    risk: "medium",
  },
  {
    id: "imageSharpening",
    regName: "imageSharpening",
    category: "nvidia",
    icon: Eye,
    color: COLORS[2],
    titleKey: "systemOptimizer.nvidia.imageSharpening",
    descKey: "systemOptimizer.nvidia.imageSharpeningDesc",
    risk: "low",
  },
  {
    id: "disableGpuPowerMgmt",
    regName: "disableGpuPowerMgmt",
    category: "nvidia",
    icon: Power,
    color: COLORS[3],
    titleKey: "systemOptimizer.nvidia.disableGpuPowerMgmt",
    descKey: "systemOptimizer.nvidia.disableGpuPowerMgmtDesc",
    risk: "medium",
  },
  {
    id: "disableHDCP",
    regName: "disableHDCP",
    category: "nvidia",
    icon: ShieldOff,
    color: COLORS[4],
    titleKey: "systemOptimizer.nvidia.disableHDCP",
    descKey: "systemOptimizer.nvidia.disableHDCPDesc",
    risk: "medium",
  },
  {
    id: "disableWriteCombining",
    regName: "disableWriteCombining",
    category: "nvidia",
    icon: Cpu,
    color: COLORS[5],
    titleKey: "systemOptimizer.nvidia.disableWriteCombining",
    descKey: "systemOptimizer.nvidia.disableWriteCombiningDesc",
    risk: "medium",
  },
  {
    id: "disableClockGating",
    regName: "disableClockGating",
    category: "nvidia",
    icon: Clock,
    color: COLORS[6],
    titleKey: "systemOptimizer.nvidia.disableClockGating",
    descKey: "systemOptimizer.nvidia.disableClockGatingDesc",
    risk: "medium",
  },
  {
    id: "disableTelemetry",
    regName: "disableTelemetry",
    category: "nvidia",
    icon: Eye,
    color: COLORS[7],
    titleKey: "systemOptimizer.nvidia.disableTelemetry",
    descKey: "systemOptimizer.nvidia.disableTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableDriverLog",
    regName: "disableDriverLog",
    category: "nvidia",
    icon: FileText,
    color: COLORS[8],
    titleKey: "systemOptimizer.nvidia.disableDriverLog",
    descKey: "systemOptimizer.nvidia.disableDriverLogDesc",
    risk: "low",
  },
  {
    id: "lockPState0",
    regName: "lockPState0",
    category: "nvidia",
    icon: Zap,
    color: COLORS[9],
    titleKey: "systemOptimizer.nvidia.lockPState0",
    descKey: "systemOptimizer.nvidia.lockPState0Desc",
    risk: "high",
  },
  {
    id: "disableMiracastOverlay",
    regName: "disableMiracastOverlay",
    category: "nvidia",
    icon: MonitorOff,
    color: COLORS[10],
    titleKey: "systemOptimizer.nvidia.disableMiracastOverlay",
    descKey: "systemOptimizer.nvidia.disableMiracastOverlayDesc",
    risk: "medium",
  },

  // ============== AMD 显卡优化 ==============
  {
    id: "shaderCache",
    regName: "shaderCache",
    category: "amd",
    icon: Cpu,
    color: COLORS[0],
    titleKey: "systemOptimizer.amd.shaderCache",
    descKey: "systemOptimizer.amd.shaderCacheDesc",
    risk: "low",
  },
  {
    id: "amdPowerOptimization",
    regName: "amdPowerOptimization",
    category: "amd",
    icon: Zap,
    color: COLORS[1],
    titleKey: "systemOptimizer.amd.amdPowerOptimization",
    descKey: "systemOptimizer.amd.amdPowerOptimizationDesc",
    risk: "medium",
  },

  // ============== Intel 显卡优化 ==============
  {
    id: "intelGraphicsOptimization",
    regName: "intelGraphicsOptimization",
    category: "intel",
    icon: Monitor,
    color: COLORS[0],
    titleKey: "systemOptimizer.intel.intelGraphicsOptimization",
    descKey: "systemOptimizer.intel.intelGraphicsOptimizationDesc",
    risk: "medium",
  },

  // ============== 系统性能调优（8 项） ==============
  {
    id: "intelTSX",
    regName: "intelTSX",
    category: "performance",
    icon: Cpu,
    color: COLORS[1],
    titleKey: "systemOptimizer.performance.intelTSX",
    descKey: "systemOptimizer.performance.intelTSXDesc",
    risk: "medium",
  },
  {
    id: "mergeSvcHost",
    regName: "mergeSvcHost",
    category: "performance",
    icon: Server,
    color: COLORS[2],
    titleKey: "systemOptimizer.performance.mergeSvcHost",
    descKey: "systemOptimizer.performance.mergeSvcHostDesc",
    risk: "medium",
  },
  {
    id: "shortenTaskTimeout",
    regName: "shortenTaskTimeout",
    category: "performance",
    icon: Clock,
    color: COLORS[3],
    titleKey: "systemOptimizer.performance.shortenTaskTimeout",
    descKey: "systemOptimizer.performance.shortenTaskTimeoutDesc",
    risk: "low",
  },
  {
    id: "shortenServiceTimeout",
    regName: "shortenServiceTimeout",
    category: "performance",
    icon: Clock,
    color: COLORS[4],
    titleKey: "systemOptimizer.performance.shortenServiceTimeout",
    descKey: "systemOptimizer.performance.shortenServiceTimeoutDesc",
    risk: "low",
  },
  {
    id: "mouseHoverDelay",
    regName: "mouseHoverDelay",
    category: "performance",
    icon: MousePointer,
    color: COLORS[5],
    titleKey: "systemOptimizer.performance.mouseHoverDelay",
    descKey: "systemOptimizer.performance.mouseHoverDelayDesc",
    risk: "low",
  },
  {
    id: "disableStartupDelay",
    regName: "disableStartupDelay",
    category: "performance",
    icon: Zap,
    color: COLORS[6],
    titleKey: "systemOptimizer.performance.disableStartupDelay",
    descKey: "systemOptimizer.performance.disableStartupDelayDesc",
    risk: "low",
  },
  {
    id: "disablePowerSaving",
    regName: "disablePowerSaving",
    category: "performance",
    icon: Power,
    color: COLORS[7],
    titleKey: "systemOptimizer.performance.disablePowerSaving",
    descKey: "systemOptimizer.performance.disablePowerSavingDesc",
    risk: "medium",
  },
  {
    id: "nvmeTuning",
    regName: "nvmeTuning",
    category: "performance",
    icon: HardDrive,
    color: COLORS[8],
    titleKey: "systemOptimizer.performance.nvmeTuning",
    descKey: "systemOptimizer.performance.nvmeTuningDesc",
    risk: "low",
  },
  {
    id: "disableMenuDelay",
    regName: "disableMenuDelay",
    category: "performance",
    icon: MousePointer,
    color: COLORS[9],
    titleKey: "systemOptimizer.performance.disableMenuDelay",
    descKey: "systemOptimizer.performance.disableMenuDelayDesc",
    risk: "low",
  },
  {
    id: "keyboardLatency",
    regName: "keyboardLatency",
    category: "performance",
    icon: Keyboard,
    color: COLORS[10],
    titleKey: "systemOptimizer.performance.keyboardLatency",
    descKey: "systemOptimizer.performance.keyboardLatencyDesc",
    risk: "low",
  },
  {
    id: "disableAutoComplete",
    regName: "disableAutoComplete",
    category: "performance",
    icon: Search,
    color: COLORS[11],
    titleKey: "systemOptimizer.performance.disableAutoComplete",
    descKey: "systemOptimizer.performance.disableAutoCompleteDesc",
    risk: "low",
  },
  {
    id: "disableWindowShake",
    regName: "disableWindowShake",
    category: "performance",
    icon: Monitor,
    color: COLORS[12],
    titleKey: "systemOptimizer.performance.disableWindowShake",
    descKey: "systemOptimizer.performance.disableWindowShakeDesc",
    risk: "low",
  },
  {
    id: "enableLowDiskCheck",
    regName: "enableLowDiskCheck",
    category: "performance",
    icon: HardDrive,
    color: COLORS[13],
    titleKey: "systemOptimizer.performance.enableLowDiskCheck",
    descKey: "systemOptimizer.performance.enableLowDiskCheckDesc",
    risk: "low",
  },
  {
    id: "disableLinkResolve",
    regName: "disableLinkResolve",
    category: "performance",
    icon: Network,
    color: COLORS[14],
    titleKey: "systemOptimizer.performance.disableLinkResolve",
    descKey: "systemOptimizer.performance.disableLinkResolveDesc",
    risk: "low",
  },
  {
    id: "excludeWUDrivers",
    regName: "excludeWUDrivers",
    category: "performance",
    icon: Cpu,
    color: COLORS[0],
    titleKey: "systemOptimizer.performance.excludeWUDrivers",
    descKey: "systemOptimizer.performance.excludeWUDriversDesc",
    risk: "medium",
  },
  {
    id: "ifeoProcessTuning",
    regName: "ifeoProcessTuning",
    category: "performance",
    icon: Cog,
    color: COLORS[1],
    titleKey: "systemOptimizer.performance.ifeoProcessTuning",
    descKey: "systemOptimizer.performance.ifeoProcessTuningDesc",
    risk: "medium",
  },

  // ============== 隐私与遥测（10 项） ==============
  {
    id: "disableTelemetrySvc",
    regName: "disableTelemetrySvc",
    category: "privacy",
    icon: Eye,
    color: COLORS[0],
    titleKey: "systemOptimizer.privacy.disableTelemetrySvc",
    descKey: "systemOptimizer.privacy.disableTelemetrySvcDesc",
    risk: "medium",
  },
  {
    id: "disableCEIP",
    regName: "disableCEIP",
    category: "privacy",
    icon: Activity,
    color: COLORS[1],
    titleKey: "systemOptimizer.privacy.disableCEIP",
    descKey: "systemOptimizer.privacy.disableCEIPDesc",
    risk: "low",
  },
  {
    id: "disableDotNetTelemetry",
    regName: "disableDotNetTelemetry",
    category: "privacy",
    icon: Code,
    color: COLORS[2],
    titleKey: "systemOptimizer.privacy.disableDotNetTelemetry",
    descKey: "systemOptimizer.privacy.disableDotNetTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableAppImpactTelemetry",
    regName: "disableAppImpactTelemetry",
    category: "privacy",
    icon: Activity,
    color: COLORS[3],
    titleKey: "systemOptimizer.privacy.disableAppImpactTelemetry",
    descKey: "systemOptimizer.privacy.disableAppImpactTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableAppImpactTelemetryAgent",
    regName: "disableAppImpactTelemetryAgent",
    category: "privacy",
    icon: Activity,
    color: COLORS[4],
    titleKey: "systemOptimizer.privacy.disableAppImpactTelemetryAgent",
    descKey: "systemOptimizer.privacy.disableAppImpactTelemetryAgentDesc",
    risk: "low",
  },
  {
    id: "disableLicenseTelemetry",
    regName: "disableLicenseTelemetry",
    category: "privacy",
    icon: Shield,
    color: COLORS[5],
    titleKey: "systemOptimizer.privacy.disableLicenseTelemetry",
    descKey: "systemOptimizer.privacy.disableLicenseTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableScheduledDiag",
    regName: "disableScheduledDiag",
    category: "privacy",
    icon: Clock,
    color: COLORS[6],
    titleKey: "systemOptimizer.privacy.disableScheduledDiag",
    descKey: "systemOptimizer.privacy.disableScheduledDiagDesc",
    risk: "low",
  },
  {
    id: "disableWebcamTelemetry",
    regName: "disableWebcamTelemetry",
    category: "privacy",
    icon: Camera,
    color: COLORS[7],
    titleKey: "systemOptimizer.privacy.disableWebcamTelemetry",
    descKey: "systemOptimizer.privacy.disableWebcamTelemetryDesc",
    risk: "medium",
  },
  {
    id: "disableWritingFeedback",
    regName: "disableWritingFeedback",
    category: "privacy",
    icon: Pen,
    color: COLORS[8],
    titleKey: "systemOptimizer.privacy.disableWritingFeedback",
    descKey: "systemOptimizer.privacy.disableWritingFeedbackDesc",
    risk: "low",
  },
  {
    id: "disableErrorReporting",
    regName: "disableErrorReporting",
    category: "privacy",
    icon: AlertTriangle,
    color: COLORS[9],
    titleKey: "systemOptimizer.privacy.disableErrorReporting",
    descKey: "systemOptimizer.privacy.disableErrorReportingDesc",
    risk: "low",
  },
  {
    id: "disableAdvertisingId",
    regName: "disableAdvertisingId",
    category: "privacy",
    icon: Megaphone,
    color: COLORS[10],
    titleKey: "systemOptimizer.privacy.disableAdvertisingId",
    descKey: "systemOptimizer.privacy.disableAdvertisingIdDesc",
    risk: "low",
  },
  {
    id: "disableAdsPromotional",
    regName: "disableAdsPromotional",
    category: "privacy",
    icon: SlidersHorizontal,
    color: COLORS[11],
    titleKey: "systemOptimizer.privacy.disableAdsPromotional",
    descKey: "systemOptimizer.privacy.disableAdsPromotionalDesc",
    risk: "low",
  },
  {
    id: "disableOnlineSpeechRecognition",
    regName: "disableOnlineSpeechRecognition",
    category: "privacy",
    icon: MicOff,
    color: COLORS[12],
    titleKey: "systemOptimizer.privacy.disableOnlineSpeechRecognition",
    descKey: "systemOptimizer.privacy.disableOnlineSpeechRecognitionDesc",
    risk: "low",
  },
  {
    id: "disableTailoredExperiences",
    regName: "disableTailoredExperiences",
    category: "privacy",
    icon: Sparkles,
    color: COLORS[13],
    titleKey: "systemOptimizer.privacy.disableTailoredExperiences",
    descKey: "systemOptimizer.privacy.disableTailoredExperiencesDesc",
    risk: "low",
  },
  {
    id: "disableMsaCloudSearch",
    regName: "disableMsaCloudSearch",
    category: "privacy",
    icon: CloudOff,
    color: COLORS[14],
    titleKey: "systemOptimizer.privacy.disableMsaCloudSearch",
    descKey: "systemOptimizer.privacy.disableMsaCloudSearchDesc",
    risk: "low",
  },
  {
    id: "disableLockScreenSpotlight",
    regName: "disableLockScreenSpotlight",
    category: "privacy",
    icon: ImageIcon,
    color: COLORS[0],
    titleKey: "systemOptimizer.privacy.disableLockScreenSpotlight",
    descKey: "systemOptimizer.privacy.disableLockScreenSpotlightDesc",
    risk: "low",
  },
  {
    id: "disableInkingDictionary",
    regName: "disableInkingDictionary",
    category: "privacy",
    icon: Pen,
    color: COLORS[1],
    titleKey: "systemOptimizer.privacy.disableInkingDictionary",
    descKey: "systemOptimizer.privacy.disableInkingDictionaryDesc",
    risk: "low",
  },
  {
    id: "disableFeedbackRequests",
    regName: "disableFeedbackRequests",
    category: "privacy",
    icon: MessageSquare,
    color: COLORS[2],
    titleKey: "systemOptimizer.privacy.disableFeedbackRequests",
    descKey: "systemOptimizer.privacy.disableFeedbackRequestsDesc",
    risk: "low",
  },
  {
    id: "disableCortana",
    regName: "disableCortana",
    category: "privacy",
    icon: MicOff,
    color: COLORS[4],
    titleKey: "systemOptimizer.privacy.disableCortana",
    descKey: "systemOptimizer.privacy.disableCortanaDesc",
    risk: "low",
  },
  {
    id: "disableNewsAndInterests",
    regName: "disableNewsAndInterests",
    category: "privacy",
    icon: Megaphone,
    color: COLORS[5],
    titleKey: "systemOptimizer.privacy.disableNewsAndInterests",
    descKey: "systemOptimizer.privacy.disableNewsAndInterestsDesc",
    risk: "low",
  },
  {
    id: "disableCloudOptimizedContent",
    regName: "disableCloudOptimizedContent",
    category: "privacy",
    icon: CloudOff,
    color: COLORS[6],
    titleKey: "systemOptimizer.privacy.disableCloudOptimizedContent",
    descKey: "systemOptimizer.privacy.disableCloudOptimizedContentDesc",
    risk: "low",
  },
  {
    id: "disableEdgeTelemetry",
    regName: "disableEdgeTelemetry",
    category: "privacy",
    icon: Chrome,
    color: COLORS[7],
    titleKey: "systemOptimizer.privacy.disableEdgeTelemetry",
    descKey: "systemOptimizer.privacy.disableEdgeTelemetryDesc",
    risk: "medium",
  },
  {
    id: "disableVisualStudioTelemetry",
    regName: "disableVisualStudioTelemetry",
    category: "privacy",
    icon: Code,
    color: COLORS[8],
    titleKey: "systemOptimizer.privacy.disableVisualStudioTelemetry",
    descKey: "systemOptimizer.privacy.disableVisualStudioTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableChromeTelemetry",
    regName: "disableChromeTelemetry",
    category: "privacy",
    icon: Chrome,
    color: COLORS[9],
    titleKey: "systemOptimizer.privacy.disableChromeTelemetry",
    descKey: "systemOptimizer.privacy.disableChromeTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableFirefoxTelemetry",
    regName: "disableFirefoxTelemetry",
    category: "privacy",
    icon: Globe,
    color: COLORS[10],
    titleKey: "systemOptimizer.privacy.disableFirefoxTelemetry",
    descKey: "systemOptimizer.privacy.disableFirefoxTelemetryDesc",
    risk: "low",
  },
  {
    id: "disableActivityFeed",
    regName: "disableActivityFeed",
    category: "privacy",
    icon: Activity,
    color: COLORS[11],
    titleKey: "systemOptimizer.privacy.disableActivityFeed",
    descKey: "systemOptimizer.privacy.disableActivityFeedDesc",
    risk: "low",
  },
  {
    id: "disableCdp",
    regName: "disableCdp",
    category: "privacy",
    icon: Boxes,
    color: COLORS[12],
    titleKey: "systemOptimizer.privacy.disableCdp",
    descKey: "systemOptimizer.privacy.disableCdpDesc",
    risk: "medium",
  },
  {
    id: "disableDiagnosticsToast",
    regName: "disableDiagnosticsToast",
    category: "privacy",
    icon: AlertTriangle,
    color: COLORS[13],
    titleKey: "systemOptimizer.privacy.disableDiagnosticsToast",
    descKey: "systemOptimizer.privacy.disableDiagnosticsToastDesc",
    risk: "low",
  },
  {
    id: "disableHandwritingSharing",
    regName: "disableHandwritingSharing",
    category: "privacy",
    icon: Pen,
    color: COLORS[14],
    titleKey: "systemOptimizer.privacy.disableHandwritingSharing",
    descKey: "systemOptimizer.privacy.disableHandwritingSharingDesc",
    risk: "low",
  },
  {
    id: "disableTextInputCollection",
    regName: "disableTextInputCollection",
    category: "privacy",
    icon: Pen,
    color: COLORS[0],
    titleKey: "systemOptimizer.privacy.disableTextInputCollection",
    descKey: "systemOptimizer.privacy.disableTextInputCollectionDesc",
    risk: "low",
  },
  {
    id: "disableInputPersonalization",
    regName: "disableInputPersonalization",
    category: "privacy",
    icon: Cog,
    color: COLORS[1],
    titleKey: "systemOptimizer.privacy.disableInputPersonalization",
    descKey: "systemOptimizer.privacy.disableInputPersonalizationDesc",
    risk: "low",
  },
  {
    id: "disableActivityUploads",
    regName: "disableActivityUploads",
    category: "privacy",
    icon: CloudOff,
    color: COLORS[2],
    titleKey: "systemOptimizer.privacy.disableActivityUploads",
    descKey: "systemOptimizer.privacy.disableActivityUploadsDesc",
    risk: "low",
  },
  {
    id: "disableMessageSync",
    regName: "disableMessageSync",
    category: "privacy",
    icon: MessageSquare,
    color: COLORS[3],
    titleKey: "systemOptimizer.privacy.disableMessageSync",
    descKey: "systemOptimizer.privacy.disableMessageSyncDesc",
    risk: "low",
  },
  {
    id: "disableSettingSync",
    regName: "disableSettingSync",
    category: "privacy",
    icon: Layers,
    color: COLORS[4],
    titleKey: "systemOptimizer.privacy.disableSettingSync",
    descKey: "systemOptimizer.privacy.disableSettingSyncDesc",
    risk: "medium",
  },
  {
    id: "disableVoiceActivation",
    regName: "disableVoiceActivation",
    category: "privacy",
    icon: MicOff,
    color: COLORS[5],
    titleKey: "systemOptimizer.privacy.disableVoiceActivation",
    descKey: "systemOptimizer.privacy.disableVoiceActivationDesc",
    risk: "low",
  },
  {
    id: "disableFindMyDevice",
    regName: "disableFindMyDevice",
    category: "privacy",
    icon: MapIcon,
    color: COLORS[6],
    titleKey: "systemOptimizer.privacy.disableFindMyDevice",
    descKey: "systemOptimizer.privacy.disableFindMyDeviceDesc",
    risk: "medium",
  },

  // ============== Windows AI 优化（9 项） ==============
  {
    id: "disableCopilot",
    regName: "disableCopilot",
    category: "ai",
    icon: Bot,
    color: COLORS[0],
    titleKey: "systemOptimizer.ai.disableCopilot",
    descKey: "systemOptimizer.ai.disableCopilotDesc",
    risk: "low",
  },
  {
    id: "disableRecallSnapshots",
    regName: "disableRecallSnapshots",
    category: "ai",
    icon: CameraOff,
    color: COLORS[1],
    titleKey: "systemOptimizer.ai.disableRecallSnapshots",
    descKey: "systemOptimizer.ai.disableRecallSnapshotsDesc",
    risk: "low",
  },
  {
    id: "blockRecallEnablement",
    regName: "blockRecallEnablement",
    category: "ai",
    icon: Ban,
    color: COLORS[2],
    titleKey: "systemOptimizer.ai.blockRecallEnablement",
    descKey: "systemOptimizer.ai.blockRecallEnablementDesc",
    risk: "low",
  },
  {
    id: "disableAiDataAnalysis",
    regName: "disableAiDataAnalysis",
    category: "ai",
    icon: Brain,
    color: COLORS[3],
    titleKey: "systemOptimizer.ai.disableAiDataAnalysis",
    descKey: "systemOptimizer.ai.disableAiDataAnalysisDesc",
    risk: "low",
  },
  {
    id: "disableClickToDo",
    regName: "disableClickToDo",
    category: "ai",
    icon: MousePointer,
    color: COLORS[4],
    titleKey: "systemOptimizer.ai.disableClickToDo",
    descKey: "systemOptimizer.ai.disableClickToDoDesc",
    risk: "low",
  },
  {
    id: "disableAiSettingsAgent",
    regName: "disableAiSettingsAgent",
    category: "ai",
    icon: Cog,
    color: COLORS[5],
    titleKey: "systemOptimizer.ai.disableAiSettingsAgent",
    descKey: "systemOptimizer.ai.disableAiSettingsAgentDesc",
    risk: "low",
  },
  {
    id: "disableAgentConnectors",
    regName: "disableAgentConnectors",
    category: "ai",
    icon: Plug,
    color: COLORS[6],
    titleKey: "systemOptimizer.ai.disableAgentConnectors",
    descKey: "systemOptimizer.ai.disableAgentConnectorsDesc",
    risk: "low",
  },
  {
    id: "disableAgentWorkspaces",
    regName: "disableAgentWorkspaces",
    category: "ai",
    icon: Boxes,
    color: COLORS[7],
    titleKey: "systemOptimizer.ai.disableAgentWorkspaces",
    descKey: "systemOptimizer.ai.disableAgentWorkspacesDesc",
    risk: "low",
  },
  {
    id: "disableRemoteAgentConnectors",
    regName: "disableRemoteAgentConnectors",
    category: "ai",
    icon: Globe,
    color: COLORS[8],
    titleKey: "systemOptimizer.ai.disableRemoteAgentConnectors",
    descKey: "systemOptimizer.ai.disableRemoteAgentConnectorsDesc",
    risk: "low",
  },

  // ============== 系统服务精简（11 项） ==============
  {
    id: "disableSensorSvc",
    regName: "disableSensorSvc",
    category: "services",
    icon: Radio,
    color: COLORS[0],
    titleKey: "systemOptimizer.services.disableSensorSvc",
    descKey: "systemOptimizer.services.disableSensorSvcDesc",
    risk: "low",
  },
  {
    id: "disableFaxSvc",
    regName: "disableFaxSvc",
    category: "services",
    icon: Phone,
    color: COLORS[1],
    titleKey: "systemOptimizer.services.disableFaxSvc",
    descKey: "systemOptimizer.services.disableFaxSvcDesc",
    risk: "low",
  },
  {
    id: "disablePrintSvc",
    regName: "disablePrintSvc",
    category: "services",
    icon: Printer,
    color: COLORS[2],
    titleKey: "systemOptimizer.services.disablePrintSvc",
    descKey: "systemOptimizer.services.disablePrintSvcDesc",
    risk: "medium",
  },
  {
    id: "disableMapsBroker",
    regName: "disableMapsBroker",
    category: "services",
    icon: MapIcon,
    color: COLORS[3],
    titleKey: "systemOptimizer.services.disableMapsBroker",
    descKey: "systemOptimizer.services.disableMapsBrokerDesc",
    risk: "low",
  },
  {
    id: "disableUCPD",
    regName: "disableUCPD",
    category: "services",
    icon: Shield,
    color: COLORS[4],
    titleKey: "systemOptimizer.services.disableUCPD",
    descKey: "systemOptimizer.services.disableUCPDDesc",
    risk: "low",
  },
  {
    id: "disableDCOM",
    regName: "disableDCOM",
    category: "services",
    icon: Server,
    color: COLORS[5],
    titleKey: "systemOptimizer.services.disableDCOM",
    descKey: "systemOptimizer.services.disableDCOMDesc",
    risk: "high",
  },
  {
    id: "disableStorageSense",
    regName: "disableStorageSense",
    category: "services",
    icon: HardDrive,
    color: COLORS[6],
    titleKey: "systemOptimizer.services.disableStorageSense",
    descKey: "systemOptimizer.services.disableStorageSenseDesc",
    risk: "low",
  },
  {
    id: "disableAutoMaintenance",
    regName: "disableAutoMaintenance",
    category: "services",
    icon: Clock,
    color: COLORS[7],
    titleKey: "systemOptimizer.services.disableAutoMaintenance",
    descKey: "systemOptimizer.services.disableAutoMaintenanceDesc",
    risk: "medium",
  },
  {
    id: "disableAppCompat",
    regName: "disableAppCompat",
    category: "services",
    icon: Shield,
    color: COLORS[8],
    titleKey: "systemOptimizer.services.disableAppCompat",
    descKey: "systemOptimizer.services.disableAppCompatDesc",
    risk: "medium",
  },
  {
    id: "disableStepRecorder",
    regName: "disableStepRecorder",
    category: "services",
    icon: Monitor,
    color: COLORS[9],
    titleKey: "systemOptimizer.services.disableStepRecorder",
    descKey: "systemOptimizer.services.disableStepRecorderDesc",
    risk: "low",
  },
  {
    id: "disablePerfTips",
    regName: "disablePerfTips",
    category: "services",
    icon: Activity,
    color: COLORS[10],
    titleKey: "systemOptimizer.services.disablePerfTips",
    descKey: "systemOptimizer.services.disablePerfTipsDesc",
    risk: "low",
  },
  {
    id: "disableRemoteRegistry",
    regName: "disableRemoteRegistry",
    category: "services",
    icon: Server,
    color: COLORS[11],
    titleKey: "systemOptimizer.services.disableRemoteRegistry",
    descKey: "systemOptimizer.services.disableRemoteRegistryDesc",
    risk: "low",
  },
  {
    id: "disableSysMain",
    regName: "disableSysMain",
    category: "services",
    icon: Server,
    color: COLORS[12],
    titleKey: "systemOptimizer.services.disableSysMain",
    descKey: "systemOptimizer.services.disableSysMainDesc",
    risk: "medium",
  },
  {
    id: "disableSystemRestore",
    regName: "disableSystemRestore",
    category: "services",
    icon: ShieldOff,
    color: COLORS[13],
    titleKey: "systemOptimizer.services.disableSystemRestore",
    descKey: "systemOptimizer.services.disableSystemRestoreDesc",
    risk: "medium",
  },
  {
    id: "disableSMBv1",
    regName: "disableSMBv1",
    category: "services",
    icon: Server,
    color: COLORS[14],
    titleKey: "systemOptimizer.services.disableSMBv1",
    descKey: "systemOptimizer.services.disableSMBv1Desc",
    risk: "low",
  },
  {
    id: "disableSMBv2",
    regName: "disableSMBv2",
    category: "services",
    icon: Server,
    color: COLORS[0],
    titleKey: "systemOptimizer.services.disableSMBv2",
    descKey: "systemOptimizer.services.disableSMBv2Desc",
    risk: "high",
  },

  // ============== 磁盘与文件系统（5 项） ==============
  {
    id: "disable8dot3",
    regName: "disable8dot3",
    category: "disk",
    icon: FileText,
    color: COLORS[0],
    titleKey: "systemOptimizer.disk.disable8dot3",
    descKey: "systemOptimizer.disk.disable8dot3Desc",
    risk: "low",
  },
  {
    id: "disableNtfsEncryption",
    regName: "disableNtfsEncryption",
    category: "disk",
    icon: ShieldOff,
    color: COLORS[1],
    titleKey: "systemOptimizer.disk.disableNtfsEncryption",
    descKey: "systemOptimizer.disk.disableNtfsEncryptionDesc",
    risk: "medium",
  },
  {
    id: "disableLastAccess",
    regName: "disableLastAccess",
    category: "disk",
    icon: HardDrive,
    color: COLORS[2],
    titleKey: "systemOptimizer.disk.disableLastAccess",
    descKey: "systemOptimizer.disk.disableLastAccessDesc",
    risk: "low",
  },
  {
    id: "disableReservedStorage",
    regName: "disableReservedStorage",
    category: "disk",
    icon: HardDrive,
    color: COLORS[3],
    titleKey: "systemOptimizer.disk.disableReservedStorage",
    descKey: "systemOptimizer.disk.disableReservedStorageDesc",
    risk: "low",
  },
  {
    id: "disableFullFsSearch",
    regName: "disableFullFsSearch",
    category: "disk",
    icon: Search,
    color: COLORS[4],
    titleKey: "systemOptimizer.disk.disableFullFsSearch",
    descKey: "systemOptimizer.disk.disableFullFsSearchDesc",
    risk: "low",
  },
  {
    id: "ntfsMftZone",
    regName: "ntfsMftZone",
    category: "disk",
    icon: HardDrive,
    color: COLORS[5],
    titleKey: "systemOptimizer.disk.ntfsMftZone",
    descKey: "systemOptimizer.disk.ntfsMftZoneDesc",
    risk: "medium",
  },

  // ============== 应用与界面（4 项） ==============
  {
    id: "disableBackgroundApps",
    regName: "disableBackgroundApps",
    category: "apps",
    icon: Layout,
    color: COLORS[0],
    titleKey: "systemOptimizer.apps.disableBackgroundApps",
    descKey: "systemOptimizer.apps.disableBackgroundAppsDesc",
    risk: "low",
  },
  {
    id: "disableEdgeStartupBoost",
    regName: "disableEdgeStartupBoost",
    category: "apps",
    icon: Chrome,
    color: COLORS[1],
    titleKey: "systemOptimizer.apps.disableEdgeStartupBoost",
    descKey: "systemOptimizer.apps.disableEdgeStartupBoostDesc",
    risk: "low",
  },
  {
    id: "slimEdgeAds",
    regName: "slimEdgeAds",
    category: "apps",
    icon: MessageSquare,
    color: COLORS[2],
    titleKey: "systemOptimizer.apps.slimEdgeAds",
    descKey: "systemOptimizer.apps.slimEdgeAdsDesc",
    risk: "low",
  },
  {
    id: "disableSearchWebView2",
    regName: "disableSearchWebView2",
    category: "apps",
    icon: Search,
    color: COLORS[3],
    titleKey: "systemOptimizer.apps.disableSearchWebView2",
    descKey: "systemOptimizer.apps.disableSearchWebView2Desc",
    risk: "low",
  },
  {
    id: "addCopyMoveContextMenu",
    regName: "addCopyMoveContextMenu",
    category: "apps",
    icon: Layout,
    color: COLORS[4],
    titleKey: "systemOptimizer.apps.addCopyMoveContextMenu",
    descKey: "systemOptimizer.apps.addCopyMoveContextMenuDesc",
    risk: "low",
  },
  {
    id: "disableStoreAutoUpdate",
    regName: "disableStoreAutoUpdate",
    category: "apps",
    icon: Chrome,
    color: COLORS[5],
    titleKey: "systemOptimizer.apps.disableStoreAutoUpdate",
    descKey: "systemOptimizer.apps.disableStoreAutoUpdateDesc",
    risk: "medium",
  },
];

export const categoryLabels: Record<OptimizerCategory, string> = {
  gaming: "systemOptimizer.category.gaming",
  nvidia: "systemOptimizer.category.nvidia",
  amd: "systemOptimizer.category.amd",
  intel: "systemOptimizer.category.intel",
  performance: "systemOptimizer.category.performance",
  privacy: "systemOptimizer.category.privacy",
  ai: "systemOptimizer.category.ai",
  services: "systemOptimizer.category.services",
  disk: "systemOptimizer.category.disk",
  apps: "systemOptimizer.category.apps",
};

export const categoryOrder: OptimizerCategory[] = [
  "gaming",
  "nvidia",
  "amd",
  "intel",
  "performance",
  "privacy",
  "ai",
  "services",
  "disk",
  "apps",
];
